package com.itservices.gpxanalyzer.chart;

public enum RequestStatus {
    ERROR_DATA_SETS_NULL,
    ERROR_LINE_DATA_SET_NULL,
    ERROR_NEW_DATA_SET_NULL,
    ERROR_INVALID_DATA_SET_AMOUNT_TO_SHOW,
    CHART_WEAK_REFERENCE_IS_NULL,
    CHART_IS_NULL,
    ERROR,
    DEFAULT,
    LOADING,
    DATA_LOADED,
    PROCESSING,
    PROCESSED,
    CHART_INITIALIZED,
    CHART_UPDATING,
    CHART_UPDATED,
    DONE
}
